### ISSUE TITLE
no coordinates for micrograph micrographs_DW/stack_*_DW.mrc

### ISSUE THREAD

**Issue by ajian-he** [rsanchezgarc/micrograph_cleaner_em#4]
I install the micrograph_cleaner by conda as suggested, when I try a simple run,

cleanMics -c Extract/job194/micrographs_DW/ -o Extract/job194/cleaned_coordinates/ -b 256 -s 1.0 -g -2 -i micrographs_DW/ --deepThr 0.5

 it comes up with this error 

Warning, no coordinates for micrograph micrographs_DW/*.mrc
Traceback (most recent call last):
  File "/home/lrss/anaconda3/envs/env_micrograph_cleaner_em/bin/cleanMics", line 11, in <module>
    sys.exit(commanLineFun())
  File "/home/lrss/anaconda3/envs/env_micrograph_cleaner_em/lib/python3.6/site-packages/micrograph_cleaner_em/cleanMics.py", line 58, in commanLineFun
    main( ** parseArgs() )
  File "/home/lrss/anaconda3/envs/env_micrograph_cleaner_em/lib/python3.6/site-packages/micrograph_cleaner_em/cleanMics.py", line 23, in main
    assert len(matchingFnames)>0, "Error, there are no matching coordinate-micrograph files"
AssertionError: Error, there are no matching coordinate-micrograph files

all those coordinate files are stored in the extract folder of relion Extract/job194/micrographs_DW/, and the micrographs folder is micrographs_DW/, any help?

**Comment by ajian-he** [comment]
figured out that is due to the file name *_extract.star, changed all to *.star to match the micrograph name, however, when execute 
cleanMics -c Extract/job211/original_coordinates/ -o Extract/job211/cleaned_coordinates/ -b 256 -s 1.0 -g -2 -i micrographs_DW/ --deepThr 0.5

AssertionError: Error, input format not understood for Extract/job211/original_coordinates/stack_00003_0_0_Dec09_10_50_05.star

what is the format recognized by this program? I use standard relion fromat

**Comment by ajian-he** [comment]
ValueError: could not convert string to float: 'stack_01840_Dec09_21.48.09_2dave_DW.mrc'

Does it mean that the coordinate file should only contain float but not string?

**Comment by ajian-he** [comment]
help,,,please!

**Comment by ajian-he** [comment]
Figured out!
the coordinate file must be float
